<?php

require_once dirname(__FILE__) . '/../../PHPUnit/Extensions/MockFunction.php';

/**
 * Test class for PHPUnit_Extensions_MockFunction.
 * Generated by PHPUnit on 2011-05-18 at 00:22:24.
 */
class PHPUnit_Extensions_MockFunctionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PHPUnit_Extensions_MockFunction
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PHPUnit_Extensions_MockFunction;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testRestore().
     */
    public function testRestore() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testInvoked().
     */
    public function testInvoked() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testExpects().
     */
    public function testExpects() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testFindMock().
     */
    public function testFindMock() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testFindTestCase().
     */
    public function testFindTestCase() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
